### ISSUE TITLE
Choose a license?

### ISSUE THREAD

**Issue by matvore** [nd/mk.java#1]
Thanks for this code! I used `mk.java` as a starting point to write a bunch of relational programming utility code. I plan to work on this even more to experiment with relational programming. Unfortunately, I can't publish any of my code since the base (your code) doesn't have a license attached to it. Would you mind choosing one?

**Comment by nd** [comment]
I've added a license. I think people in miniKanren mailing list (https://groups.google.com/forum/#!forum/minikanren) will be interested in relation programming experiments.

**Comment by matvore** [comment]
Can I trouble you to include the full text of the license, with your name in the Copyright line - either in README.md or a LICENSE file? I am advised that citing a license by name is not "correct" and the full text needs to be there. I would send you a pull request but I don't know if my authoring your license would create some legal gray area.

Sorry for the hassle, and hopefully you will find this worth your effort once my improvements are available.

**Comment by nd** [comment]
Here you go :)

**Comment by matvore** [comment]
Thank you, sir!
